env:
  matrix:
    - LIBJWT_BUILD_METHOD=autotools
language: c
compiler:
  - gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libjansson-dev check libssl-dev lcov curl
script:
  - if [ "$LIBJWT_BUILD_METHOD" = "autotools" ]; then autoreconf -i && ./configure && make check; fi
